{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1fb12be1-b1d5-45b4-93cf-d481391a96a9",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Noopy\\anaconda3\\envs\\plant_ml_1004\\Lib\\site-packages\\tqdm\\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "* Running on local URL:  http://127.0.0.1:7861\n",
      "* Running on public URL: https://9ffbcd896681850b0e.gradio.live\n",
      "\n",
      "This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div><iframe src=\"https://9ffbcd896681850b0e.gradio.live\" width=\"100%\" height=\"500\" allow=\"autoplay; camera; microphone; clipboard-read; clipboard-write;\" frameborder=\"0\" allowfullscreen></iframe></div>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/plain": []
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import json\n",
    "import os\n",
    "import cv2\n",
    "import gradio as gr\n",
    "import numpy as np\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "from PIL import Image, ImageOps\n",
    "from torchvision import models, transforms\n",
    "\n",
    "# =============================================================\n",
    "# 1. 載入模型權重與類別標籤\n",
    "# =============================================================\n",
    "device = torch.device(\n",
    "    \"cuda\"\n",
    "    if torch.cuda.is_available()\n",
    "    else (\"mps\" if torch.backends.mps.is_available() else \"cpu\")\n",
    ")\n",
    "\n",
    "if not os.path.exists(\"class_names.json\"):\n",
    "    raise FileNotFoundError(\"❌ 找不到 class_names.json！\")\n",
    "\n",
    "with open(\"class_names.json\", \"r\", encoding=\"utf-8\") as f:\n",
    "    class_names = json.load(f)\n",
    "\n",
    "num_classes = len(class_names)\n",
    "\n",
    "if not os.path.exists(\"tomato_resnet18.pth\"):\n",
    "    raise FileNotFoundError(\"❌ 找不到 tomato_resnet18.pth！\")\n",
    "\n",
    "model = models.resnet18(weights=None)\n",
    "model.fc = nn.Linear(model.fc.in_features, num_classes)\n",
    "model.load_state_dict(torch.load(\"tomato_resnet18.pth\", map_location=device))\n",
    "model = model.to(device)\n",
    "model.eval()\n",
    "\n",
    "# 影像轉換規則 (與訓練時一致)\n",
    "val_transforms = transforms.Compose(\n",
    "    [\n",
    "        transforms.Resize((224, 224)),\n",
    "        transforms.ToTensor(),\n",
    "        transforms.Normalize(\n",
    "            mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]\n",
    "        ),\n",
    "    ]\n",
    ")\n",
    "\n",
    "\n",
    "# =============================================================\n",
    "# 2. 病斑面積比例計算 (保持與第一段原解析度計算邏輯一致)\n",
    "# =============================================================\n",
    "def calculate_infection_ratio_from_cv(img_bgr):\n",
    "    # 轉換顏色空間\n",
    "    img_hsv = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2HSV)\n",
    "\n",
    "    # 1. 葉片範圍判定\n",
    "    lower_green = np.array([35, 40, 40])\n",
    "    upper_green = np.array([85, 255, 255])\n",
    "    mask_green = cv2.inRange(img_hsv, lower_green, upper_green)\n",
    "\n",
    "    lower_diseased = np.array([10, 30, 30])\n",
    "    upper_diseased = np.array([35, 255, 255])\n",
    "    mask_diseased = cv2.inRange(img_hsv, lower_diseased, upper_diseased)\n",
    "\n",
    "    leaf_mask = cv2.bitwise_or(mask_green, mask_diseased)\n",
    "\n",
    "    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))\n",
    "    leaf_mask = cv2.morphologyEx(leaf_mask, cv2.MORPH_CLOSE, kernel)\n",
    "    leaf_mask = cv2.morphologyEx(leaf_mask, cv2.MORPH_OPEN, kernel)\n",
    "\n",
    "    # 2. 病斑範圍判定\n",
    "    lower_dark = np.array([0, 0, 0])\n",
    "    upper_dark = np.array([180, 255, 80])\n",
    "    mask_dark = cv2.inRange(img_hsv, lower_dark, upper_dark)\n",
    "\n",
    "    raw_lesion_mask = cv2.bitwise_or(mask_diseased, mask_dark)\n",
    "    lesion_mask = cv2.bitwise_and(\n",
    "        raw_lesion_mask, raw_lesion_mask, mask=leaf_mask\n",
    "    )\n",
    "    lesion_mask = cv2.morphologyEx(lesion_mask, cv2.MORPH_OPEN, kernel)\n",
    "\n",
    "    # 3. 面積統計\n",
    "    total_leaf_pixels = cv2.countNonZero(leaf_mask)\n",
    "    lesion_pixels = cv2.countNonZero(lesion_mask)\n",
    "\n",
    "    if total_leaf_pixels == 0:\n",
    "        return 0.0, leaf_mask, lesion_mask\n",
    "\n",
    "    infection_ratio = (lesion_pixels / total_leaf_pixels) * 100.0\n",
    "\n",
    "    # 轉為 3 通道以確保 Gradio 順暢顯示\n",
    "    leaf_mask_rgb = cv2.cvtColor(leaf_mask, cv2.COLOR_GRAY2RGB)\n",
    "    lesion_mask_rgb = cv2.cvtColor(lesion_mask, cv2.COLOR_GRAY2RGB)\n",
    "\n",
    "    return infection_ratio, leaf_mask_rgb, lesion_mask_rgb\n",
    "\n",
    "\n",
    "# =============================================================\n",
    "# 3. Gradio 網頁介面專用診斷邏輯\n",
    "# =============================================================\n",
    "def predict_tomato_disease(input_pil_img):\n",
    "    if input_pil_img is None:\n",
    "        return None, \"未選擇圖片\", \"請上傳或點擊選擇一張圖片。\", None, None\n",
    "\n",
    "    # 自動修正 EXIF 圖片轉向\n",
    "    input_pil_img = ImageOps.exif_transpose(input_pil_img)\n",
    "\n",
    "    # 1. AI 深度學習模型預測\n",
    "    input_tensor = val_transforms(input_pil_img).unsqueeze(0).to(device)\n",
    "    with torch.no_grad():\n",
    "        outputs = model(input_tensor)\n",
    "        probs = torch.nn.functional.softmax(outputs[0], dim=0)\n",
    "\n",
    "    confidences = {\n",
    "        class_names[i]: float(probs[i]) for i in range(num_classes)\n",
    "    }\n",
    "\n",
    "    top_pred = max(confidences, key=confidences.get)\n",
    "    pred_label_lower = top_pred.lower()\n",
    "\n",
    "    # 2. 判斷是否為晚疫病並進行病斑計算 (對齊第一段邏輯)\n",
    "    if \"late\" in pred_label_lower or \"blight\" in pred_label_lower:\n",
    "        img_np = np.array(input_pil_img)\n",
    "        img_bgr = cv2.cvtColor(img_np, cv2.COLOR_RGB2BGR)\n",
    "\n",
    "        infection_ratio, leaf_mask_rgb, lesion_mask_rgb = (\n",
    "            calculate_infection_ratio_from_cv(img_bgr)\n",
    "        )\n",
    "\n",
    "        ratio_str = f\"{infection_ratio:.2f}%\"\n",
    "\n",
    "        if infection_ratio < 15.0:\n",
    "            advice = f\"💡 **防護建議**：輕度晚疫病感染 (病斑佔 {infection_ratio:.1f}%)，請即刻剪除病葉並施用有機銅劑保護。\"\n",
    "        elif infection_ratio < 45.0:\n",
    "            advice = f\"⚠️ **防護建議**：中度晚疫病感染 (病斑佔 {infection_ratio:.1f}%)，需隔離該植株並使用系統性殺菌劑控制擴散。\"\n",
    "        else:\n",
    "            advice = f\"🚨 **警告建議**：重度晚疫病感染 (病斑佔 {infection_ratio:.1f}%)！建議移除植株並銷毀，避免孢子傳播。\"\n",
    "\n",
    "        return (\n",
    "            confidences,\n",
    "            ratio_str,\n",
    "            advice,\n",
    "            leaf_mask_rgb,\n",
    "            lesion_mask_rgb,\n",
    "        )\n",
    "    else:\n",
    "        # 非晚疫病或健康狀態\n",
    "        advice = f\"✅ **檢測結果**：預測為 **{top_pred}**。葉片狀況良好或非晚疫病，無需計算病斑面積。\"\n",
    "        return confidences, \"N/A\", advice, None, None\n",
    "\n",
    "\n",
    "# =============================================================\n",
    "# 4. 建立 Gradio UI\n",
    "# =============================================================\n",
    "example_images = []\n",
    "if os.path.exists(\"./tomato-test.jpg\"):\n",
    "    example_images.append([\"./tomato-test.jpg\"])\n",
    "\n",
    "with gr.Blocks(title=\"番茄葉片病害 AI 診斷系統\") as demo:\n",
    "    gr.Markdown(\"#番茄葉片病害 AI 診斷與病斑面積分析系統\")\n",
    "    gr.Markdown(\n",
    "        \"您可以**點擊上傳選擇電腦圖片**、**貼上剪貼簿圖片**，或是**點擊下方範例圖片**進行診斷：\"\n",
    "    )\n",
    "\n",
    "    with gr.Row():\n",
    "        with gr.Column(scale=1):\n",
    "            image_input = gr.Image(\n",
    "                type=\"pil\",\n",
    "                label=\"選擇或上傳圖片\",\n",
    "                sources=[\"upload\", \"clipboard\"],\n",
    "            )\n",
    "\n",
    "            if example_images:\n",
    "                gr.Examples(\n",
    "                    examples=example_images,\n",
    "                    inputs=image_input,\n",
    "                    label=\"💡 點擊下方範例圖片直接測試：\",\n",
    "                )\n",
    "\n",
    "            btn_submit = gr.Button(\"🔍 開始診斷\", variant=\"primary\")\n",
    "\n",
    "        with gr.Column(scale=1):\n",
    "            label_output = gr.Label(\n",
    "                label=\"AI 辨識類別與信心度 (Confidence Level)\"\n",
    "            )\n",
    "            ratio_output = gr.Textbox(\n",
    "                label=\"病斑面積比例 (Infection Ratio)\"\n",
    "            )\n",
    "            advice_output = gr.Markdown(label=\"診斷與防護建議\")\n",
    "\n",
    "    with gr.Row():\n",
    "        leaf_mask_output = gr.Image(\n",
    "            label=\"葉片範圍遮罩 (Leaf Mask)\", type=\"numpy\"\n",
    "        )\n",
    "        lesion_mask_output = gr.Image(\n",
    "            label=\"病斑範圍遮罩 (Lesion Mask)\", type=\"numpy\"\n",
    "        )\n",
    "\n",
    "    btn_submit.click(\n",
    "        fn=predict_tomato_disease,\n",
    "        inputs=[image_input],\n",
    "        outputs=[\n",
    "            label_output,\n",
    "            ratio_output,\n",
    "            advice_output,\n",
    "            leaf_mask_output,\n",
    "            lesion_mask_output,\n",
    "        ],\n",
    "    )\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    demo.launch(server_name=\"0.0.0.0\", server_port=7860)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "563732c7-bf89-4802-b62a-15fde751249e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.17"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
